name: Build on macOS

on:
  create:
    tags:
      - v*
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build macOS
        run: ./build.sh --macos
      
      - name: Build ios
        run: ./build.sh --ios
      
      - name: Build android
        run: ./build.sh --android
      
      - name: Upload libraries
        uses: actions/upload-artifact@v3
        with:
          name: build-macOS
          path: release
