name: Build on macOS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-10.15

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build macOS
        run: ./build.sh --macos
      
      - name: Build ios
        run: ./build.sh --macos
      
      - name: Build android
        run: ./build.sh --android
